app/discobase/urls.py
from django.urls import path
from discobase import views

app_name = "discobase"

urlpatterns = [
    path(
        "record_list/",
        views.RecordListView.as_view(),
        name="record_list",
    ),
    path(
        "<int:pk>/",
        views.RecordDetailView.as_view(),
        name="record_detail",
    ),
    path(
        "trxcredit_list/",
        views.TrxCreditListView.as_view(),
        name="trxcredit_list",
    ),
    path(
        "trxcredit_chart/",
        views.TrxCreditChartView.as_view(),
        name="trxcredit_chart",
    ),
    path(
        "search_TEMP/",
        views.search_TEMP,
        name="search_TEMP",
    ),
]

app/django_disco/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django Admin (with random silly custom url to harden against attacks)
    path("raph-is-the-admin/", admin.site.urls),
    # Django user management (login, logout)
    path("accounts/", include("allauth.urls")),
    # Local apps
    path("", include("pages.urls")),
    path("discobase/", include("discobase.urls")),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)  # for local use only

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

app/pages/urls.py
from django.contrib import admin
from django.urls import path

from pages.views import AboutPageView, HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

app/templates/_base.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}DiscoBase{% endblock title %}</title>
    <!-- Bootstrap CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Death Metal Disco 2</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-targ\ et="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Tog\ gle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'discobase:record_list' %}">Records</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'discobase:trxcredit_chart' %}">Trx-Credits</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'about' %}">About</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:login' %}">Admin</a>
                        </li>                    
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
                <!-- Search django-book p.222-->
                <form class="d-flex" action="{% url 'discobase:record_list' %}" method="GET">
                    <input class="form-control me-2" type="search" name="q" placeholder="Record Search" aria-label="Record Search">
                    <button class="btn btn-outline-success" type=submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <!-- Container-->
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Bootstrap JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
    <!-- Custom JavaScript, all js preferably to be loaded at the end -->
    <script> src="{%static 'js/base.js' %}"</script>
</body>

</html>

app/templates/about.html
{% extends "_base.html" %}

{%block title %}About{% endblock title %}

{% block content %}
<h1>About Page</h1>
{% endblock content %}

app/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

    <title>Document</title>
</head>

<body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'discobase:list_record' %}">Record List</a>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}

</body>

</html>

app/templates/home.html
{% extends "_base.html" %}
{% load static %}

{% block title %}Home{% endblock title %}
    
{% block content %}
    <h1>This is the discobase homepage.</h1>
    <img class="recordcover" src="{% static 'images/cover.jpg' %}">
{% endblock content %}